# Generated by Django 4.2.11 on 2024-05-03 05:43

from django.db import migrations, models


def forwards(apps, schema_editor):
    Choice = apps.get_model("polls", "Choice")
    Choice.objects.update(order=models.F('_order'))


def backwards(apps, scheme_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=9999999),
        ),
        migrations.RunPython(forwards, backwards, elidable=True),
    ]
