# Generated by Django 4.2.11 on 2024-05-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('order',)},
        ),
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to=None,
        ),
    ]
