# Generated by Django 4.2.11 on 2024-05-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('_order',)},
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='order',
            new_name='_order',
        ),
    ]
